version: '2'

networks:
  faust_default:

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: faust:latest
  #   container_name: faust
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ../../.:/app:z
  #   env_file:
  #     - .env
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - faust_default

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - faust_default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - faust_default